version: "3"
services:
  cryptosnipe_staging:
    build: . # build from Dockerfile in current directory
    ports: # map port 4000 on host to port 4000 in container
      - "4000:4000"
    environment: # set environment variables
      - NODE_ENV=production
networks:
  default:
    external:
      name: reverse-proxy