---
name: Deploy API

on:
    workflow_dispatch:
      inputs:
        ENVIRONMENT:
          type: choice
          description: 'Environment to deploy to'
          required: true
          options:
            - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Update bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/lux/cryptosnipe/${{ github.event.inputs.ENVIRONMENT }}/CryptoWhaleSnipe
            git config --global --add safe.directory /home/lux/cryptosnipe/${{ github.event.inputs.ENVIRONMENT }}/CryptoWhaleSnipe
            git stash
            git pull
            git checkout ${{ steps.extract_branch.outputs.branch }}
            git stash
            git pull
            docker stop cryptowhalesnipe_cryptosnipe${{ github.event.inputs.ENVIRONMENT }}_1 || echo "No container running, building new one"
            docker rm cryptowhalesnipe_cryptosnipe${{ github.event.inputs.ENVIRONMENT }}_1 || echo "No container running, building new one"
            docker rmi cryptowhalesnipe_cryptosnipe${{ github.event.inputs.ENVIRONMENT }} || echo "No image found, building new one"
            docker-compose -f docker-compose-${{ github.event.inputs.ENVIRONMENT }}.yml up -d --build